---

- name: Run the automated AWX playbook locally
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: create directoruy for awx
      file: path=~/awx state=directory

    - name: install nodejs package
      apt:
        name: nodejs
        state: latest

    - name: download ansible awx
      git:
        repo: 'https://github.com/ansible/awx.git'
        dest: '~/awx'
        version: 'devel'
        update: 'yes'
        force: yes
        accept_hostkey: yes

    - name: Install the latest verision of package "python-pip"
      apt:
        name: python-pip
        state: latest

    - name: Install the latest verision of package "docker.io"
      command: apt-get install -y docker.io

    - name: Start docker
      command: systemctl start docker

    - name: Enable docker on boot 
      command: systemctl enable docker

    - name: Install docker python-pip
      command: pip install docker

    - name: Upgrade Ansible to latest version
      command: pip install --upgrade ansible